name: Deploy VibeCode to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy /public contents to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r public/* docs/

      - name: Commit & Push docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy to /docs for GitHub Pages" || echo "No changes to commit"
          git push
